### ISSUE TITLE
TODO List to get app running

### ISSUE THREAD

**Issue by mattdavis0351** [mattdavis0351/tipper#2]
- [x] Parse cmd line flags, Cobra
- [x] Get a bill total
- [x] Specify tip %
- [x] Return tip amnt and total to user in a non ugly way

## Always keep code modular... don't fuck up in front of people
